spring.application.name=northwind-traders-springboot-2.0

spring.datasource.url=jdbc:mysql://localhost:3306/northwind
spring.datasource.username=root
spring.datasource.password=Yearup2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

